services:
  db:
    image: postgres:16-alpine
    container_name: maven-postgres-db
    environment:
      POSTGRES_DB: maven_postgres
      POSTGRES_USER: maven_postgres_user
      POSTGRES_PASSWORD: maven_postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U maven_postgres_user -d maven_postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
